//------------------------------------------------------------------------------------------------------Welcome Message Start Here------------------------------------------------------------------------------------------------------
var welcomed = false;
function welcomeMessage() {
	if (!welcomed){
		welcomed = true;
		
		var messages = [
			"Now Featuring Flying Whales",
			"Coming to a Platform Near You",
			"Now with New Ideas",
			"Shy, a Guy, and Ready to Die",
			"More Creative than Ever!",
			"Now Owns Their Own Coffee Machine",
			"Sleep is for the Weak",
			"Cooler than Double-sided Tape",
			"More Reviews Soon!",
			"Cooler than Room Temperature",
			"Sweeter than Black Coffee",
			"Taken with a Grain of Rice",
			"Pancakes are Best",
			"This Website Only Kinda Sucks",
			"New Backgrounds in the Works",
			"Uses Too Many Candles",
			"Please Help Me Use Makeup",
			"FTL: Faster Than Light is great",
			"Fan of Axolotls",
			"My Shade of Pink is Best",
			"I'll Fix the Website... Eventually",
			"Now Wears a Lab Coat",
			"How to Indie Dev?",
			"Pronounced suh-shi-mus",
			"Graduated from Trade School!",
			"Caster of Stick-Horses",
			"Wears Socks and Slippers",
			"Mugs are My Religion",
			"I Use Linux BTW",
			"SPACE IS KOOL!!",
			"Providing Dad-Energy Since 19",
			"Command Hooks are Great",
			"Now Ripping Off Minecraft",
			"Carl is Waiting.",
			"Now Moderately Useful!",
			"Go Binge GDC",
			"Next Confinement Episode When??",
			"Snails are Mollusk Cows.",
			"Cows are Mammal Snails.",
			"Watch out for Big Condiment",
			"SLIME RANCHER 2 2022!!",
			"Plorp is a Good Egg",
			"All my Homies Hate Trig",
			"Whale Onsie Penguins are so 2019",
			"Now Adding Suffering",
			"Now with Half the Jank!",
			"Engineering Art",
			"Mr Brew is Pure",
			"Calculating Colours",
			"I'll Build a Portfolio Maybe",
			"Calculus Makes Me Sad",
			"Mojang Hire Me Plz",
			"Paws of Mischief",
			"Carl's Wrath",
			"Maker",
			"make_me_",
			"Drinks Litres of Coffee",
			"Check Out My Free Assets",
			"Ziggs Main",
			"Check Out My Free Code",
			"Generating Colours",
			"Mr Big Ideas",
			"My Hands are Clamy",
			"Turtle-Ducks are Cute",
			"Website Code Eludes Me",
			"IOS Please Work",
			"Mr Brew is a Baby Angel",
			"Creme of Wheat Enjoyer",
			"How to Art?",
			"Colour Pallets Elude Me",
			"Silly Cat Game Go Brrr",
			"Follow Abi.Toads on Instagram",
			"Follow Faunwood on Instagram",
			"Maker of Wallpaper Dumps",
			"I can do a Handstand!",
			"Hat Enthusiast",
			"Yet to Watch StarWars",
			"Heart Machine Hire Me Plz",
			"Provider of Spiced Meat",
			"Sussymus",
			"I've got a Headache",
			"Graduated Trade School",
			"Night Owl",
			"Mr Brew is Crazy",
			"Bananas Make Brew Angery",
			"Deniably Mainstream",
			"*dabs*",
			"Crying to be Beautiful",
			"Eyes Wide Open",
			"Enjoyer of Plushies",
			"Java < C#",
			"Two-Timing Tony",
			"Monomi Park Hire Me Plz",
			"No Stopping the Womblacongus",
			"Goober Sweep",
			"Womblacongus Amongus",
			"Mr Brew is a Floppy Boi"
		]
		var messageChoose = Math.floor(Math.random() * (messages.length));
		var messageChosen = messages[messageChoose];
		
		document.getElementById('welcome').innerHTML = messageChosen;
	}
	
}